### ISSUE TITLE
SVN not found when installing projects.

### ISSUE THREAD

**Issue by benspector3** [OperationSpark/opspark#28]
using version 3.0.3 

```bash
Installing project bouncing-box, please wait...
Failure installing project
Failure initializing
Error: Error: Error: Command failed: svn co https://github.com/OperationSpark/bouncing-box/trunk --password 1e4466fa0dc2faa1a0c578ae165c1989efee4646 /home/ubuntu/environment/projects/bouncing-box
/bin/sh: 1: svn: not found

    at /home/ubuntu/.nvm/versions/node/v8.16.0/lib/node_modules/opspark/controller/janitor.js:13:11
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

```

**Comment by benspector3** [comment]
Please add a check for `svn` when installing the `opspark` tool and if it is not found, run the following bash command:

`sudo apt-get install subversion`

**Comment by andyn190** [comment]
What IDE were you using that got this error? codenvy or cloud9?

**Comment by benspector3** [comment]
@andyn190 Cloud9
